"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory
$character"""

add_newline = false
scan_timeout = 30

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[git_status]
disabled = true

[package]
disabled = true
